=== spiewaj/songbook/_site/song.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://21wdh.staszic.waw.pl" xmlns:xs="http://www.w3.org/2001/XMLSchema"  xmlns:song="http://21wdh.staszic.waw.pl">
    <xs:element name="song" type="song:songType"/>
    <xs:complexType name="creatorType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="solo" />
                            <xs:enumeration value="band" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="chType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="a" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="rowType" mixed="true">
        <xs:sequence>
            <xs:element type="song:chType" name="ch" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="important_over" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true"/> <!--Chords should be showed above the lyric-->
                    <xs:enumeration value="false"/><!--Chords may be showed above the lyric (but it's usually not needed)-->
                    <xs:enumeration value="never"/><!--Chords are only shown on the left side-->
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="sidechords" type="xs:string" use="optional"/>
        <xs:attribute name="style" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="instr" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="blockType" mixed="true">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element type="song:rowType" name="row" maxOccurs="unbounded" minOccurs="0" />
            <xs:element type="song:bisType" name="bis" maxOccurs="unbounded" minOccurs="0" />
        </xs:choice>
        <xs:attribute name="type" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string" >
                    <xs:enumeration value="verse" />
                    <xs:enumeration value="chorus" />
                    <xs:enumeration value="other" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>


    <xs:complexType name="bisType">
        <xs:sequence>
            <xs:element type="song:rowType" name="row" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
        <xs:attribute type="xs:integer" name="times" use="optional"/>
    </xs:complexType>

    <xs:complexType name="blocklinkType">
        <xs:attribute type="xs:integer" name="blocknb" use="required"/>
    </xs:complexType>

    <xs:complexType name="lyricType">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element type="song:blockType" name="block" maxOccurs="unbounded" minOccurs="0" />
            <xs:element type="song:blocklinkType" name="blocklink" maxOccurs="unbounded" minOccurs="0"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="guitarType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:byte" name="barre"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="musicType">
        <xs:all>
            <xs:element type="song:guitarType" name="guitar" minOccurs="0" maxOccurs="1"/>
        </xs:all>
        <xs:attribute type="xs:string" name="metre" use="optional"/>
    </xs:complexType>
    <xs:complexType name="keywordsType">
        <xs:sequence>
            <xs:element type="xs:string" name="keyword" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="doneType">
        <xs:all>
            <xs:element type="xs:string" name="text" maxOccurs="1" minOccurs="0"/>
            <xs:element type="xs:string" name="chords" maxOccurs="1" minOccurs="0"/>
            <xs:element type="xs:string" name="authors" maxOccurs="1" minOccurs="0"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="verificatorsType">
        <xs:sequence>
            <xs:element type="xs:string" name="verificator" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="statusType">
        <xs:all>
            <xs:element type="song:doneType" name="done" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:verificatorsType" name="verificators"  minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="to_do"  minOccurs="0" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="songType">
        <xs:all>
            <xs:element type="xs:string" name="alias" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:creatorType" name="text_author" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="comment" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:creatorType" name="composer" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:creatorType" name="artist" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="translator" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="original_title" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:lyricType" name="lyric" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:musicType" name="music" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:keywordsType" name="keywords" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="album" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="genre" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:statusType" name="status" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="music_source" minOccurs="0" maxOccurs="1"/>
        </xs:all>
        <xs:attribute type="xs:string" name="title" use="required"/>
    </xs:complexType>
</xs:schema>

=== spiewaj/songbook/songs/pl/custom/21wdh/Prawo_dzungli.xml
<?xml version="1.0" encoding="utf-8"?>
<song title="Prawo dżungli" xmlns="http://21wdh.staszic.waw.pl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://21wdh.staszic.waw.pl https://spiewaj.com/song.xsd">
	<alias></alias>
	<text_author type="solo">Rudyard Kipling</text_author>
	<comment>Na potrzeby młodszoharcerskie…</comment>
	<composer type="solo">Michał Korch</composer>
	<artist type="solo"></artist>
	<translator>Józef Birkenmajer</translator>
	<original_title></original_title>
	<lyric xmlns="http://21wdh.staszic.waw.pl">
		<block type="verse">
			<row important_over="true">
				<ch a="e"/>Oto jest zbiór praw dż<ch a="H7"/>ungli — jak niebo wieczysty, niem<ch a="e"/>ylny,</row>
			<row important_over="true">G<ch a="e"/>inie wilk, co je łamie; w<ch a="H7"/>ilk, co ich słucha jest szczęśl<ch a="e"/>iwy i silny.</row>
			<row important_over="true">Jak pn<ch a="e"/>ącza, co pi<ch a="H7"/>eń opas<ch a="e"/>ują, tak Pr<ch a="e"/>awo wkoło nas się w<ch a="H7"/>ini<ch a="C"/>e,</row>
			<bis times="2">
				<row important_over="true">Bo w<ch a="e"/>ilk jest s<ch a="H7"/>iłą druż<ch a="C"/>yn<ch a="D"/>y, a s<ch a="e"/>iła w<ch a="D"/>ilka w druż<ch a="e"/>ynie.</row>
			</bis>
		</block>
		<block type="verse">
			<row important_over="false">P<ch a="e"/>ij do syta, lecz w mi<ch a="H7"/>arę. Kąp się codziennie od k<ch a="e"/>ity do głowy,</row>
			<row important_over="false">A p<ch a="e"/>omnij, że dzień jest od sp<ch a="H7"/>ania, a noc przeznaczona na ł<ch a="e"/>owy.</row>
			<row important_over="false">Ni<ch a="e"/>echaj się sz<ch a="H7"/>akal łasi tygr<ch a="e"/>ysom! Lecz t<ch a="e"/>y, gdy wyr<ch a="H7"/>ośniesz, o, szcz<ch a="C"/>enię,</row>
			<bis times="2">
				<row important_over="false">Pami<ch a="e"/>ętaj, że w<ch a="H7"/>ilk jest ł<ch a="C"/>owc<ch a="D"/>ą — i s<ch a="e"/>am ma zdob<ch a="D"/>ywać jedz<ch a="e"/>enie.</row>
			</bis>
		</block>
		<block type="verse">
			<row important_over="false">Gdy spotk<ch a="e"/>ają się dwa stada i ni<ch a="H7"/>e chcą sobie ustąpić uprz<ch a="e"/>ejmie,</row>
			<row important_over="false">Leż spok<ch a="e"/>ojnie, bo może starsz<ch a="H7"/>yzna bezkrwawo sp<ch a="e"/>ór ten rozejmie.</row>
			<row important_over="false">N<ch a="e"/>ora jest w<ch a="H7"/>ilka schroni<ch a="e"/>eniem, lecz gd<ch a="e"/>y wykopał ją n<ch a="H7"/>azbyt wid<ch a="C"/>ocznie,</row>
			<bis times="2">
				<row important_over="false">R<ch a="e"/>ada mu prz<ch a="H7"/>eśle przestr<ch a="C"/>og<ch a="D"/>ę, aż<ch a="e"/>eby się prz<ch a="D"/>eniósł niezwł<ch a="e"/>ocznie.</row>
			</bis>
		</block>
		<block type="verse">
			<row important_over="false">Gdyś z<ch a="e"/>aczął łów przed półn<ch a="H7"/>ocą, milcz — nie budź lasu szczek<ch a="e"/>aniem,</row>
			<row important_over="false">Bo spł<ch a="e"/>oszysz nam wszelką zwierz<ch a="H7"/>ynę i my bez łupu zost<ch a="e"/>aniem.</row>
			<row important_over="false">P<ch a="e"/>oluj dla si<ch a="H7"/>ebie, dla szcz<ch a="e"/>eniąt, dla druhów. Kr<ch a="e"/>ew t<ch a="H7"/>aka nie br<ch a="C"/>udzi!</row>
			<bis times="2">
				<row important_over="false">L<ch a="e"/>ecz bez potrz<ch a="H7"/>eby nie p<ch a="C"/>ol<ch a="D"/>uj! Po siedmi<ch a="e"/>okroć wara pol<ch a="D"/>ować na l<ch a="e"/>udzi!</row>
			</bis>
		</block>
		<block type="verse">
			<row important_over="false">Gdy p<ch a="e"/>orwiesz zdobycz słabsz<ch a="H7"/>emu, nie pożeraj wszystkiego w próżn<ch a="e"/>ości.</row>
			<row important_over="false">N<ch a="e"/>ędzarz jest w Prawa opi<ch a="H7"/>ece, zostaw mu choć skórę i k<ch a="e"/>ości!</row>
			<row important_over="false">Zd<ch a="e"/>obycz druż<ch a="H7"/>yny ma sł<ch a="e"/>użyć za j<ch a="e"/>adło c<ch a="H7"/>ałej dr<ch a="C"/>użynie,</row>
			<bis times="2">
				<row important_over="false">A kt<ch a="e"/>o tę zd<ch a="H7"/>obycz chciał <ch a="C"/>uni<ch a="D"/>eść do wł<ch a="e"/>asnej n<ch a="D"/>ory, niech zg<ch a="e"/>inie!</row>
			</bis>
		</block>
		<block type="verse">
			<row important_over="false">Wilcz<ch a="e"/>yca ma prawo do l<ch a="H7"/>eża. Gdy samcom powiodą się ł<ch a="e"/>owy,</row>
			<row important_over="false">W<ch a="e"/>olno jej żądać dziesi<ch a="H7"/>ęcin dla wilcząt — i nigdy nie dozna odm<ch a="e"/>owy!</row>
			<row important_over="false">Wilk — <ch a="e"/>ojciec jest p<ch a="H7"/>anem w swej n<ch a="e"/>orze. To w<ch a="e"/>olny myśl<ch a="H7"/>iwiec włócz<ch a="C"/>ęga!</row>
			<bis times="2">
				<row important_over="false">S<ch a="e"/>ądzi go j<ch a="H7"/>eno R<ch a="C"/>ad<ch a="D"/>a, a wł<ch a="e"/>adza dr<ch a="D"/>użyny go nie dosi<ch a="e"/>ęga.</row>
			</bis>
		</block>
		<block type="verse">
			<row important_over="false">Gdy Pr<ch a="e"/>awo jest w czymś niedokł<ch a="H7"/>adne, szukajcie pomocy w swym h<ch a="e"/>erszcie:</row>
			<row important_over="false">On st<ch a="e"/>arszy, mocniejszy i m<ch a="H7"/>ędrszy — więc jego przepisów się dzi<ch a="e"/>erżcie!</row>
			<row important_over="false">T<ch a="e"/>akie są Pr<ch a="H7"/>awa Puszcz<ch a="e"/>ańskie. Wyl<ch a="e"/>iczyć j<ch a="H7"/>e — niepodobi<ch a="C"/>eństwo!</row>
			<bis times="2">
				<row important_over="false">Lecz s<ch a="e"/>ercem Pr<ch a="H7"/>awa, gł<ch a="C"/>ową i k<ch a="D"/>oścem j<ch a="e"/>est… p<ch a="D"/>osłusz<ch a="e"/>eństwo!</row>
			</bis>
		</block>
	</lyric>
	
	<music metre="4/4">
		<guitar/>
	</music>
	<keywords></keywords>
	<album></album>
	<genre></genre>
	<status>
		<done>
			<text/>
			<authors/>
			<chords>chord positioning</chords>
		</done>
		<verificators>
			<verificator>Michał Korch</verificator>
			
		</verificators>
		<to_do></to_do>
	</status>
	<music_source></music_source>
</song>

=== spiewaj/songbook/songs/pl/poezja/dla_michasia.xml
<?xml version="1.0" encoding="utf-8"?>
<song title="Dla Michasia" xmlns="http://21wdh.staszic.waw.pl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://21wdh.staszic.waw.pl https://spiewaj.com/song.xsd">
	<alias></alias>
	<text_author type="solo"></text_author>
	<comment>Nie znam autorów!!!</comment>
	<composer type="solo"></composer>
	<artist type="solo"></artist>
	<translator></translator>
	<original_title></original_title>
	<lyric xmlns="http://21wdh.staszic.waw.pl">
		<block type="verse">
			<row important_over="true">Nie wierz<ch a="D"/>yłem, dobry B<ch a="G"/>oże,</row>
			<row important_over="true">Że się zd<ch a="D"/>arzyć tyle może,</row>
			<row important_over="true">Że cię ki<ch a="G"/>edyś, mały s<ch a="A"/>ynku, będę mi<ch a="D"/>ał.</row>
			<row important_over="true">Spadłeś z ni<ch a="G"/>eba mi ak<ch a="A"/>urat,</row>
			<row important_over="true">Kiedy sz<ch a="D"/>edłem z głową w chm<ch a="G"/>urach —</row>
			<row important_over="true">-- Niedosp<ch a="D"/>any, skacow<ch a="A"/>any i jak p<ch a="G"/>al<ch a="A"/>ec s<ch a="D"/>am.</row>
		</block>
		<block type="chorus">
			<row important_over="true">Dam Ci pl<ch a="G"/>ecak p<ch a="A"/>ełen m<ch a="D"/>arzeń,</row>
			<row important_over="true">Grać na<ch a="G"/>uczę n<ch a="A"/>a git<ch a="D"/>arze,</row>
			<row important_over="true">Na bar<ch a="G"/>ana Ci<ch a="Fis"/>ę przeni<ch a="h"/>osę<ch a="G"/></row>
			<row important_over="true">Przez świat sm<ch a="D"/>utny j<ch a="A"/>ak kal<ch a="G"/>osze.<ch a="A"/><ch a="D"/></row>
		</block>
		<block type="verse">
			<row important_over="false">Miejsca z<ch a="D"/>agrzać nie umi<ch a="G"/>ałem,</row>
			<row important_over="false">Trochę gr<ch a="D"/>ałem, malowałem,</row>
			<row important_over="false">Życie m<ch a="G"/>i się nieust<ch a="A"/>annie wychyl<ch a="D"/>ało z ram.</row>
			<row important_over="false">Spadłeś z ni<ch a="G"/>eba mi ak<ch a="A"/>urat,</row>
			<row important_over="false">Kiedy sz<ch a="D"/>edłem z głową w chm<ch a="G"/>urach —</row>
			<row important_over="false">Niedosp<ch a="D"/>any, skacow<ch a="A"/>any i jak p<ch a="G"/>al<ch a="A"/>ec s<ch a="D"/>am.</row>
		</block>
		<blocklink blocknb="2"/>
		<block type="verse">
			<row important_over="false">Może ki<ch a="D"/>edyś Ci op<ch a="G"/>owiem,</row>
			<row important_over="false">Kim są l<ch a="D"/>udzie, a kim człowiek,</row>
			<row important_over="false">O jaszcz<ch a="G"/>urkach w skórze k<ch a="A"/>obiet, które s<ch a="D"/>ączą jad.</row>
			<row important_over="false">Może ki<ch a="G"/>edyś — a na r<ch a="A"/>azie</row>
			<row important_over="false">Dam Ci pl<ch a="D"/>ecak pełen m<ch a="G"/>arzeń</row>
			<row important_over="false">I poni<ch a="D"/>osę na bar<ch a="A"/>ana przez parsz<ch a="G"/>yw<ch a="A"/>y świ<ch a="D"/>at.</row>
		</block>
		<blocklink blocknb="2"/>
	</lyric>
	<music metre="4/4">
		<guitar barre="0"/>
	</music>
	<keywords></keywords>
	<album></album>
	<genre></genre>
	<status>
		<done>
			<text/>
			<chords>chord positioning</chords>
		</done>
		<verificators>
			<verificator>Michał Korch</verificator>
		</verificators>
		<to_do>Nie znam autorów!!!</to_do>
	</status>
	<music_source></music_source>
</song>

=== spiewaj/songbook/songs/pl/kabaret/dus_golabki.xml
<?xml version="1.0" encoding="utf-8"?>
<song xmlns="http://21wdh.staszic.waw.pl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://21wdh.staszic.waw.pl https://spiewaj.com/song.xsd" title="Duś, duś gołąbki">
  <text_author type="solo">Artur Andrus</text_author>
  <comment/>
  <artist type="band">Artur Andrus</artist>
  <lyric>
    <block type="other">
      <row important_over="false" style="instr"> <ch a="d"/><ch a="E7"/><ch a="A7"/><ch a="A"/><ch a="d"/></row>
    </block>
    <block type="verse">
      <row important_over="true"><ch a="d"/>Na Podkarpaciu, w prastarych lasach,</row>
      <row important_over="true">Gdzie niebo czysto nie<ch a="E7"/>bieskie,</row>
      <row important_over="true">Pani Te<ch a="A7"/>resa była na wczasach,</row>
      <row important_over="true"><ch a="A"/> Przez dwa tygodnie i z <ch a="d"/>pieskiem.</row>
      <row important_over="true">A niedaleko w ceglanym bloku,</row>
      <row important_over="true">Mieszka ozdoba tej <ch a="E7"/>dziczy,</row>
      <row important_over="true">Brunecik z <ch a="A7"/>wąsem o sarnim wzroku,</row>
      <row important_over="true"><ch a="A"/> Czyli miejscowy leś<ch a="d"/>niczy.</row>
    </block>
    <block type="chorus">
      <row important_over="true"><ch a="D"/>Duś, duś go<ch a="A7"/>łąbki,</row>
      <row important_over="true"><ch a="A"/>Jadą, jadą w <ch a="D"/>gości,</row>
      <row important_over="true">Duś, duś go<ch a="A7"/>łąbki,</row>
      <row important_over="true"><ch a="A"/>Oda do &quot;radości&quot;.<ch a="D"/></row>
    </block>
    <block type="verse">
      <row important_over="false">On by jej <ch a="d"/>z drzewa nastrącał szyszek,</row>
      <row important_over="false">I kochał by ją naj<ch a="E7"/>czulej,</row>
      <row important_over="false">Ale Te<ch a="A7"/>resa i leśnik Zbyszek</row>
      <row important_over="false"><ch a="A"/>Się nie spotkali w <ch a="d"/>ogóle.</row>
      <row important_over="false">Pani Teresa całymi dniami</row>
      <row important_over="false">Się wyleguje pod <ch a="E7"/>słońcem,</row>
      <row important_over="false">A on w tym <ch a="A7"/>lesie chemikaliami,</row>
      <row important_over="false"><ch a="A"/> Dokarmia dzikie zas<ch a="d"/>krońce.</row>
    </block>
    <blocklink blocknb="3"/>
    <block type="verse">
      <row important_over="false">Ona się <ch a="d"/>lubi przyglądać żabom,</row>
      <row important_over="false">I czytać historię <ch a="E7"/>Gniezna,</row>
      <row important_over="false">Trochę się <ch a="A7"/>męczy, bo widzi słabo,</row>
      <row important_over="false"><ch a="A"/> I wszystkich liter też <ch a="d"/>nie zna.</row>
      <row important_over="false">On, kiedy las zaniesie się ciszą,</row>
      <row important_over="false">Leci jak wiatr przez roz<ch a="E7"/>łogi</row>
      <row important_over="false">Do pewnej <ch a="A7"/>Jadźki, o której piszą</row>
      <row important_over="false"><ch a="A"/> Doktorat z dermato<ch a="d"/>logii.</row>
    </block>
    <block type="verse">
      <row important_over="false" style="instr"> <ch a="d"/><ch a="E7"/><ch a="A7"/><ch a="A"/><ch a="d"/></row>
      <row important_over="false">(... tu już jest czas na rozchełstaną choreografię,</row>
      <row important_over="false">ona jest rozchełstana od początku,</row>
      <row important_over="false">trzy miesiące nad nią pracowałem</row>
      <row important_over="false">i takie są efekty...)</row>
    </block>
    <block type="verse">
      <row important_over="false"><ch a="d"/>Smutno się skończy moja piosenka:</row>
      <row important_over="false">Teresa umrze od <ch a="E7"/>słońca,</row>
      <row important_over="false">Leśnik od <ch a="A7"/>Jadźki, w okrutnych mękach,</row>
      <row important_over="false"><ch a="A"/> A piesek od zas<ch a="d"/>krońca,</row>
      <row important_over="false">Zostanie po Teresie saszetka,</row>
      <row important_over="false">Po psie obróżka z kol<ch a="E7"/>czykiem,</row>
      <row important_over="false">A po le<ch a="A7"/>śniczym mała plakietka,</row>
      <row important_over="false"><ch a="A"/> Tak, jestem Europejczykiem.</row>
    </block>
    <blocklink blocknb="3"/>
    <block type="verse">
      <row important_over="false">Odpowiedzi na zagadkę konkursowa,</row>
      <row important_over="false">Jak ma na imię Teresa?</row>
      <row important_over="false">Kierować do Nadleśnictwa Strzałowo,</row>
      <row important_over="false">Można też pekaesem wysłać esemesa.</row>
    </block>
    <block type="verse">
      <row important_over="false"><ch a="D"/>Duś, duś go<ch a="A7"/>łąbki,</row>
      <row important_over="false"><ch a="A"/>Pali się pod <ch a="D"/>gruszą,</row>
      <row important_over="false">Duś, albo <ch a="A7"/>nie duś,</row>
      <row important_over="false"><ch a="A"/>Same się poduszą.<ch a="D"/></row>
    </block>
  </lyric>
  <keywords/>
  <genre>Piosenka kabaretowa</genre>
  <status>
    <done/>
    <verificators/>
  </status>
</song>

=== spiewaj/songbook/songs/pl/pop/ale_to_juz_bylo.xml
<?xml version="1.0" encoding="utf-8"?>
<song xmlns="http://21wdh.staszic.waw.pl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://21wdh.staszic.waw.pl https://spiewaj.com/song.xsd" title="Ale to już było">
  <text_author type="solo">Andrzej Sikorowski</text_author>
  <composer type="solo">Andrzej Sikorowski</composer>
  <artist type="solo">Maryla Rodowicz</artist>
  <lyric>
    <block type="verse">
      <row important_over="false" style="instr"> <ch a="G"/><ch a="F"/><ch a="G"/><ch a="F"/><ch a="G"/></row>
      <row important_over="true">Z wielu <ch a="C"/>pieców się <ch a="G"/>jadło <ch a="C"/>chleb</row>
      <row important_over="true">Bo od <ch a="d"/>lat przyglądam się <ch a="G"/>światu</row>
      <row important_over="true">Nieraz <ch a="C"/>rano za<ch a="G"/>bolał <ch a="C"/>łeb</row>
      <row important_over="true">I mó<ch a="d"/>wili zmiana kli<ch a="G"/>matu</row>
      <row important_over="true">Czasem <ch a="e"/>trafił się wielki <ch a="d"/>raut</row>
      <row important_over="true">Albo <ch a="F"/>feta proleta<ch a="G"/>riatu</row>
      <row important_over="true">Czasem <ch a="e"/>podróż w najlepszym z <ch a="d"/>aut</row>
      <row important_over="true">Częściej <ch a="F"/>szare drogi po<ch a="G"/>wiatu</row>
    </block>
    <block type="chorus">
      <row important_over="true">Ale to już <ch a="F"/>było<ch a="G"/> i nie wróci <ch a="C"/>więcej</row>
      <row important_over="true">I choć <ch a="e"/>tyle się zdarzyło to do <ch a="F"/>przodu</row>
      <row important_over="true">Wciąż wyrywa głupie <ch a="C"/>serce</row>
      <row important_over="true">Ale to już <ch a="F"/>było<ch a="G"/>, znikło gdzieś za <ch a="C"/>nami</row>
      <row important_over="true">Choć w pa<ch a="e"/>pierach lat przybyło to na<ch a="F"/>prawdę</row>
      <row important_over="true">Wciąż jesteśmy tacy <ch a="C"/>sami</row>
    </block>
    <block type="verse">
      <row important_over="false" style="instr"> <ch a="G"/><ch a="F"/><ch a="G"/><ch a="F"/><ch a="G"/></row>
    </block>
    <block type="verse">
      <row important_over="false">Na re<ch a="C"/>gale ko<ch a="G"/>lekcja <ch a="C"/>płyt</row>
      <row important_over="false">I wy<ch a="d"/>wiadów pełne ga<ch a="G"/>zety</row>
      <row important_over="false">Za ok<ch a="C"/>nami ko<ch a="G"/>lejny <ch a="C"/>świt</row>
      <row important_over="false">I w sy<ch a="d"/>pialni dzieci od<ch a="G"/>dechy</row>
      <row important_over="false">One <ch a="e"/>lecą droga do <ch a="d"/>gwiazd</row>
      <row important_over="false">Przez nie<ch a="F"/>bieski ocean <ch a="G"/>nieba</row>
      <row important_over="false">Ale <ch a="e"/>przecież za jakiś <ch a="d"/>czas</row>
      <row important_over="false">Będą <ch a="F"/>mogły same za<ch a="G"/>śpiewać</row>
    </block>
    <block type="chorus">
      <row important_over="false">Ale to już <ch a="G"/>było<ch a="A"/> i nie wróci <ch a="D"/>więcej</row>
      <row important_over="false">I choć <ch a="fis"/>tyle się zdarzyło to do <ch a="G"/>przodu</row>
      <row important_over="false">Wciąż wyrywa głupie <ch a="D"/>serce<ch a="D"/></row>
      <row important_over="false">Ale to już <ch a="G"/>było (ale to już było)<ch a="A"/>, znikło gdzieś za <ch a="D"/>nami</row>
      <row important_over="false">Choć w pa<ch a="fis"/>pierach lat przybyło to na<ch a="G"/>prawdę</row>
      <row important_over="false">Wciąż jesteście tacy <ch a="D"/>sami<ch a="D"/> </row>
    </block>
    <block type="chorus">
      <row important_over="false"> Ale to już <ch a="G"/>było<ch a="A"/> i nie wróci <ch a="D"/>więcej</row>
      <row important_over="false">I choć <ch a="fis"/>tyle się zdarzyło to do <ch a="G"/>przodu...</row>
    </block>
  </lyric>
  <keywords/>
  <album>1992</album>
  <status>
    <done/>
    <verificators/>
  </status>
</song>

=== spiewaj/songbook/songs/pl/poezja/jam_DoZP.xml
<?xml version="1.0" encoding="utf-8"?>
<song xmlns="http://21wdh.staszic.waw.pl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://21wdh.staszic.waw.pl https://spiewaj.com/song.xsd" title="Jam">
  <alias>Wiosenny</alias>
  <artist type="band">Dom o Zielonych Progach</artist>
  <lyric>
    <block type="verse">
      <row important_over="true"><ch a="C"/>Jam jest ziemia, co pod<ch a="G"/>piera stopy</row>
      <row important_over="true"><ch a="a"/>Jam jest wiatr, <ch a="F"/>co rozwiewa włosy</row>
      <row important_over="true"><ch a="C"/>Jam jest deszcz, co o<ch a="G"/>bmywa twarz</row>
      <row important_over="true"><ch a="a"/>Jam jest słońce,<ch a="F"/> co osusza skórę</row>
    </block>
    <block type="chorus">
      <bis times="2">
        <row important_over="false">Jam jest nic, jam jest nic, i wiele</row>
        <row important_over="false">Jam jest ten, co płacze i ten co się śmieje </row>
      </bis>
    </block>
    <block type="verse">
      <row important_over="false">On jest ciepłem, co rozgrzewa ciało</row>
      <row important_over="false">On jest chmurą, co osłania mnie</row>
      <row important_over="false">On jest mgłą, co łagodzi ranek</row>
      <row important_over="false">On jest ciepłem, które mieszka we mnie</row>
    </block>
    <block type="chorus">
      <bis times="2">
        <row important_over="false">On jest nic, on jest nic, niewiele</row>
        <row important_over="false">On jest ten, co płacze i ten co się śmieje</row>
      </bis>
    </block>
  </lyric>
  <keywords/>
  <status>
    <done/>
    <verificators/>
  </status>
</song>
