=== spiewaj/songbook/_site/song.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://21wdh.staszic.waw.pl" xmlns:xs="http://www.w3.org/2001/XMLSchema"  xmlns:song="http://21wdh.staszic.waw.pl">
    <xs:element name="song" type="song:songType"/>
    <xs:complexType name="creatorType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="solo" />
                            <xs:enumeration value="band" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="chType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="a" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="rowType" mixed="true">
        <xs:sequence>
            <xs:element type="song:chType" name="ch" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="important_over" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true"/> <!--Chords should be showed above the lyric-->
                    <xs:enumeration value="false"/><!--Chords may be showed above the lyric (but it's usually not needed)-->
                    <xs:enumeration value="never"/><!--Chords are only shown on the left side-->
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="sidechords" type="xs:string" use="optional"/>
        <xs:attribute name="style" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="instr" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="blockType" mixed="true">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element type="song:rowType" name="row" maxOccurs="unbounded" minOccurs="0" />
            <xs:element type="song:bisType" name="bis" maxOccurs="unbounded" minOccurs="0" />
        </xs:choice>
        <xs:attribute name="type" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string" >
                    <xs:enumeration value="verse" />
                    <xs:enumeration value="chorus" />
                    <xs:enumeration value="other" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>


    <xs:complexType name="bisType">
        <xs:sequence>
            <xs:element type="song:rowType" name="row" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
        <xs:attribute type="xs:integer" name="times" use="optional"/>
    </xs:complexType>

    <xs:complexType name="blocklinkType">
        <xs:attribute type="xs:integer" name="blocknb" use="required"/>
    </xs:complexType>

    <xs:complexType name="lyricType">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element type="song:blockType" name="block" maxOccurs="unbounded" minOccurs="0" />
            <xs:element type="song:blocklinkType" name="blocklink" maxOccurs="unbounded" minOccurs="0"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="guitarType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:byte" name="barre"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="musicType">
        <xs:all>
            <xs:element type="song:guitarType" name="guitar" minOccurs="0" maxOccurs="1"/>
        </xs:all>
        <xs:attribute type="xs:string" name="metre" use="optional"/>
    </xs:complexType>
    <xs:complexType name="keywordsType">
        <xs:sequence>
            <xs:element type="xs:string" name="keyword" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="doneType">
        <xs:all>
            <xs:element type="xs:string" name="text" maxOccurs="1" minOccurs="0"/>
            <xs:element type="xs:string" name="chords" maxOccurs="1" minOccurs="0"/>
            <xs:element type="xs:string" name="authors" maxOccurs="1" minOccurs="0"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="verificatorsType">
        <xs:sequence>
            <xs:element type="xs:string" name="verificator" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="statusType">
        <xs:all>
            <xs:element type="song:doneType" name="done" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:verificatorsType" name="verificators"  minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="to_do"  minOccurs="0" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="songType">
        <xs:all>
            <xs:element type="xs:string" name="alias" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:creatorType" name="text_author" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="comment" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:creatorType" name="composer" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:creatorType" name="artist" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="translator" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="original_title" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:lyricType" name="lyric" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:musicType" name="music" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:keywordsType" name="keywords" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="album" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="genre" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:statusType" name="status" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="music_source" minOccurs="0" maxOccurs="1"/>
        </xs:all>
        <xs:attribute type="xs:string" name="title" use="required"/>
    </xs:complexType>
</xs:schema>

=== spiewaj/songbook/songs/pl/pop/warszawa_tlove.xml
<?xml version="1.0" encoding="utf-8"?>
<song xmlns="http://21wdh.staszic.waw.pl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://21wdh.staszic.waw.pl https://spiewaj.com/song.xsd" title="Warszawa">
  <comment/>
  <artist type="band">T.Love</artist>
  <lyric>
    <block type="verse">
      <row important_over="true">Za <ch a="G"/>oknem zimowo zaczyna się dzień</row>
      <row important_over="true">Za<ch a="a"/>czynam kolejny dzień ży<ch a="F"/>cia</row>
      <row important_over="true">Wy<ch a="G"/>glądam przez okno, na oczach mam sen</row>
      <row important_over="true">A <ch a="a"/>Grochów się budzi z przepi<ch a="F"/>cia</row>
      <row important_over="true">Wy<ch a="G"/>pity alkohol uderza w tętnice</row>
      <row important_over="true">Au<ch a="a"/>tobus tapla się w śnie<ch a="F"/>gu</row>
      <row important_over="true">Z<ch a="G"/>za szyby oglądam betonu stolicę</row>
      <row important_over="true">Już<ch a="a"/> jestem na drugim jej brze<ch a="F"/>gu</row>
    </block>
    <block type="chorus">
      <row important_over="true">Gdy <ch a="C"/>patrzę w twe <ch a="G"/>oczy, zmę<ch a="a"/>czone jak <ch a="F"/>moje</row>
      <row important_over="true">To <ch a="C"/>kocham to<ch a="G"/> miasto, zmę<ch a="a"/>czone jak <ch a="F"/> ja</row>
      <row important_over="true">Gdzie <ch a="C"/> Hitler i <ch a="G"/> Stalin zro<ch a="a"/>bili, co <ch a="F"/>swoje</row>
      <row important_over="true">Gdzie <ch a="C"/>wiosna <ch a="G"/>spaliną <ch a="F"/>oddycha</row>
    </block>
    <block type="verse">
      <row important_over="false">Kra<ch a="G"/>kowskie Przedmieście zalane jest słońcem</row>
      <row important_over="false">Wi<ch a="a"/>rujesz jak obłok, wy<ch a="F"/>nurzasz się z bramy</row>
      <row important_over="false">A<ch a="G"/> ja jestem głodny, tak bardzo głodny</row>
      <row important_over="false">Ko<ch a="a"/>chanie, nakarmisz mnie <ch a="F"/>snami</row>
      <row important_over="false">Zi<ch a="G"/>elony Żoliborz, pieprzony Żoliborz</row>
      <row important_over="false">Roz<ch a="a"/>kwita na drzewach, na krze<ch a="F"/>wach</row>
      <row important_over="false">Ście<ch a="G"/>kami z rzeki kompletnie pijany</row>
      <row important_over="false">Chcę <ch a="a"/>krzyczeć, chcę ryczeć, chcę ś<ch a="F"/>piewać</row>
    </block>
    <blocklink blocknb="2"/>
    <block type="other">
      <row important_over="false"/>
      <bis times="4">
        <row important_over="false" style="instr"> <ch a="G"/><ch a="a"/><ch a="F"/></row>
      </bis>
      <row important_over="false" style="instr"> <ch a="C"/><ch a="G"/><ch a="C"/><ch a="G"/><ch a="C"/><ch a="G"/><ch a="C"/><ch a="G"/><ch a="C"/><ch a="G"/><ch a="C"/></row>
      <row important_over="false" style="instr"> <ch a="C"/><ch a="G"/><ch a="C"/><ch a="G"/><ch a="C"/><ch a="G"/><ch a="C"/><ch a="G"/><ch a="F"/><ch a="F"/></row>
    </block>
    <block type="verse">
      <row important_over="false">Je<ch a="G"/>sienią zawsze zaczyna się szkoła</row>
      <row important_over="false">A w k<ch a="a"/>najpach zaczyna się <ch a="F"/>picie</row>
      <row important_over="false">Jest <ch a="G"/>tłoczno i duszno, olewa nas kelner</row>
      <row important_over="false">I <ch a="a"/>tak skończymy o ś<ch a="F"/>wicie</row>
      <row important_over="false">Je<ch a="G"/>sienią zawsze myślę o latach</row>
      <row important_over="false">Tak <ch a="a"/>starych, jak te kamie<ch a="F"/>nice</row>
      <row important_over="false">Je<ch a="G"/>sienią o zmroku przechodzę z tobą</row>
      <row important_over="false">Przez <ch a="a"/>pełne kasztanów ul<ch a="F"/>ice</row>
    </block>
    <blocklink blocknb="2"/>
  </lyric>
  <keywords/>
  <genre>Rock</genre>
  <status>
    <done/>
    <verificators/>
  </status>
</song>

=== spiewaj/songbook/songs/pl/pop/Winda_do_nieba.xml
<?xml version="1.0" encoding="UTF-8"?>
<song xmlns="http://21wdh.staszic.waw.pl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://21wdh.staszic.waw.pl https://spiewaj.com/song.xsd" title="Windą do nieba">
	<artist type="band">Dwa Plus Jeden</artist>
	<lyric xmlns="http://21wdh.staszic.waw.pl">
		<block type="verse">
			<row important_over="false">Mój piękny panie, raz zobaczony w technikolorze<ch a="C"/><ch a="a"/><ch a="G"/></row>
			<row important_over="false">Piszę do pana ostatni list<ch a="F"/><ch a="G"/><ch a="C"/></row>
			<row important_over="false">Już mi lusterko z tym pana zdjęciem też nie pomoże<ch a="G"/><ch a="a"/><ch a="F"/></row>
			<row important_over="false">Pora mi dzisiaj do ślubu iść<ch a="C"/><ch a="G"/><ch a="C"/></row>
		</block>
		<block type="verse">
			<row important_over="false">Mój piękny panie ja go nie kocham, taka jest prawda</row>
			<row important_over="false">Pan główną rolę gra w każdym śnie</row>
			<row important_over="false">Ale dziewczyna przez życie nie może iść całkiem sama</row>
			<row important_over="false">Życie jest życiem pan przecież wie</row>
		</block>
		<block type="chorus">
			<row important_over="false">Już mi niosą suknię z welonem<ch a="F"/><ch a="G"/><ch a="C"/><ch a="a"/></row>
			<row important_over="false">Już Cyganie czekają z muzyką</row>
			<row important_over="false">Koń do taktu zamiata ogonem</row>
			<row important_over="false">Mendelsonem stukają kopyta</row>
		</block>
		<block type="verse">
			<row important_over="false">Jeszcze ryżem sypną na szczęście</row>
			<row important_over="false">Gości tłum coś fałszywie odśpiewa</row>
			<row important_over="false">Złoty krążek mi wcisną na rękę</row>
			<bis times="3">
				<row important_over="false">I powiozą mnie windą do nieba<ch a="F"/><ch a="G"/><ch a="C"/><ch a="G"/></row>
			</bis>
		</block>
		<block type="verse">
			<row important_over="false">Mój piękny panie z tego wszystkiego nie mogłam zasnąć</row>
			<row important_over="false">Więc nie mógł mi się pan przyśnić dziś</row>
			<row important_over="false">I tak odchodzę bez pożegnania jakby z nienacka</row>
			<row important_over="false">Ktoś między nami zatrzasnął drzwi</row>
		</block>
		<blocklink blocknb="3"/>
	</lyric>
	<music>
		<guitar/>
	</music>
	<status>
		<verificators><verificator>Krzysiek Cz.</verificator>
			
		</verificators>
		<done/>
		<to_do></to_do>
	</status>
	<keywords/>
	<alias></alias>
	<text_author type="solo"></text_author>
	<composer type="solo"></composer>
	<music_source></music_source>
	<original_title></original_title>
	<translator></translator>
	<album></album>
	<genre></genre>
	<comment></comment>
</song>

=== spiewaj/songbook/songs/pl/poezja/Krakow_Piwna_7.xml
<?xml version="1.0" encoding="utf-8"?>
<song xmlns="http://21wdh.staszic.waw.pl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://21wdh.staszic.waw.pl https://spiewaj.com/song.xsd" title="Kraków, Piwna 7">
  <text_author type="solo">Andrzej Sikorowski</text_author>
  <artist type="band">Pod Budą</artist>
  <lyric>
    <block type="verse">
      <row important_over="never"><ch a="C"/>Byłem u wróżki - Piwna 7<ch a="F"/><ch a="G"/><ch a="C"/></row>
      <row important_over="never"><ch a="e"/>Wysokie kręte schody<ch a="a"/><ch a="e"/><ch a="G"/></row>
      <row important_over="never"><ch a="C"/>Ile mi jeszcze chciałem wiedzieć<ch a="F"/><ch a="G"/><ch a="C"/></row>
      <row important_over="never"><ch a="e"/>Upłynie w Wiśle wody<ch a="a"/><ch a="e"/><ch a="G"/></row>
      <row important_over="never"><ch a="C"/>Jaka mnie kiedyś czeka bieda<ch a="F"/><ch a="G"/><ch a="C"/></row>
      <row important_over="never"><ch a="e"/>Lub jakie urodzaje<ch a="a"/><ch a="e"/><ch a="G"/></row>
      <row important_over="never"><ch a="C"/>Czy mi gitarę przyjdzie sprzedać<ch a="F"/><ch a="G"/><ch a="C"/></row>
      <row important_over="never"><ch a="e"/>Czy lecieć na Hawaje<ch a="a"/><ch a="e"/><ch a="G"/></row>
      <row important_over="never"><ch a="a"/>A wróżka puka<ch a="e"/></row>
      <row important_over="never"><ch a="a"/>W szkalną kulę<ch a="e"/></row>
      <row important_over="never"><ch a="a"/>I mówi do mnie czule<ch a="e"/><ch a="G"/></row>
    </block>
    <block type="chorus">
      <row important_over="never"><ch a="C"/>Przed tobą sława<ch a="G"/><ch a="C"/></row>
      <row important_over="never"><ch a="C"/>Wieczna zabawa<ch a="G"/><ch a="C"/></row>
      <row important_over="never"><ch a="F"/>Wszystko jak z nut<ch a="G"/></row>
      <row important_over="never"><ch a="F"/>Pieniędzy w bród<ch a="G"/></row>
      <row important_over="never"><ch a="C"/>Wspaniałe płyty<ch a="G"/><ch a="C"/></row>
      <row important_over="never"><ch a="C"/>Piękne kobiety<ch a="G"/><ch a="C"/></row>
      <row important_over="never"><ch a="F"/>Zdrowie jak dzwon<ch a="G"/></row>
      <row important_over="never"><ch a="F"/>Wygodny tron<ch a="G"/></row>
    </block>
    <block type="verse">
      <row important_over="never"><ch a="C"/>Żegnam staruszkę lekki cały<ch a="F"/><ch a="G"/><ch a="C"/></row>
      <row important_over="never"><ch a="e"/>I ruszam w dół po schodach<ch a="a"/><ch a="e"/><ch a="G"/></row>
      <row important_over="never"><ch a="C"/>Nagle potykam się o mały<ch a="F"/><ch a="G"/><ch a="C"/></row>
      <row important_over="never"><ch a="e"/>Wyjątek w jej prognozach<ch a="a"/><ch a="e"/><ch a="G"/></row>
      <row important_over="never"><ch a="C"/>I myślę tak spadając z hukiem<ch a="F"/><ch a="G"/><ch a="C"/></row>
      <row important_over="never"><ch a="e"/>Niby dojrzała gruszka<ch a="a"/><ch a="e"/><ch a="G"/></row>
      <row important_over="never"><ch a="C"/>W końcu przyszedłem po naukę<ch a="F"/><ch a="G"/><ch a="C"/></row>
      <row important_over="never"><ch a="e"/>Zatem niech żyje wróżka<ch a="a"/><ch a="e"/><ch a="G"/></row>
      <row important_over="never"><ch a="a"/>Niech częściej puka<ch a="e"/></row>
      <row important_over="never"><ch a="a"/>W szklaną kulę<ch a="e"/></row>
      <row important_over="never"><ch a="a"/>I mówi do nas czule<ch a="e"/><ch a="G"/></row>
    </block>
    <block type="verse">
      <bis times="2">
        <row important_over="never"><ch a="C"/>Przed wami sława<ch a="G"/><ch a="C"/></row>
        <row important_over="never"><ch a="C"/>Wieczna zabawa<ch a="G"/><ch a="C"/></row>
        <row important_over="never"><ch a="F"/>Wszystko jak z nut<ch a="G"/></row>
        <row important_over="never"><ch a="F"/>Pieniędzy w bród<ch a="G"/></row>
        <row important_over="never"><ch a="C"/>Wspaniałe płyty<ch a="G"/><ch a="C"/></row>
        <row important_over="never"><ch a="C"/>Piękne kobiety<ch a="G"/><ch a="C"/></row>
        <row important_over="never"><ch a="F"/>Zdrowie jak dzwon<ch a="G"/></row>
        <row important_over="never"><ch a="F"/>Wygodny tron<ch a="G"/></row>
      </bis>
    </block>
  </lyric>
  <music>
    <guitar barre="2"/>
  </music>
  <keywords/>
  <album>Zmowa Z Zegarem</album>
  <genre>Poezja śpiewana</genre>
  <status>
    <done>
      <authors/>
    </done>
    <verificators/>
  </status>
</song>

=== spiewaj/songbook/songs/pl/poezja/Mur_2.xml
<?xml version="1.0" encoding="utf-8"?>
<song xmlns="http://21wdh.staszic.waw.pl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://21wdh.staszic.waw.pl https://spiewaj.com/song.xsd" title="Mur 2">
  <alias/>
  <text_author type="band"/>
  <comment/>
  <composer type="solo"/>
  <artist type="band">Zespół Reprezentacyjny</artist>
  <translator/>
  <original_title/>
  <lyric>
    <block type="verse">
      <row important_over="false"><ch a="e"/>Stary Swiset kiedyś mówił mi<ch a="H7"/><ch a="e"/></row>
      <row important_over="false"><ch a="e"/>Staliśmy w bramie, był świt<ch a="H7"/></row>
      <row important_over="false"><ch a="C"/>Gdy oczekiwaliśmy na słońca wschód<ch a="H7"/><ch a="C"/><ch a="a"/></row>
      <row important_over="false"><ch a="e"/>I samochodów rósł szum<ch a="H7"/><ch a="e"/></row>
      <row important_over="false"><ch a="e"/>Mówił mi czy muru nie widzisz<ch a="H7"/><ch a="e"/></row>
      <row important_over="false"><ch a="e"/>Wszystkich nas trzyma ten mur<ch a="H7"/></row>
      <row important_over="false"><ch a="C"/>Gdy nie będziemy bronić się<ch a="H"/><ch a="C"/><ch a="a"/></row>
      <row important_over="false"><ch a="e"/>Zagrodzi nam każdą z dróg<ch a="H7"/><ch a="e"/></row>
    </block>
    <block type="chorus">
      <row important_over="false"><ch a="H7"/>Gdy uderzymy runie mur<ch a="e"/></row>
      <row important_over="false"><ch a="H7"/>Nie może przecież wiecznie trwać<ch a="e"/></row>
      <row important_over="false"><ch a="a"/>Na pewno runie, runie, runie<ch a="e"/></row>
      <row important_over="false"><ch a="H7"/>Nie pozostanie po nim ślad<ch a="e"/></row>
      <row important_over="false"><ch a="H7"/>Jeśli uderzysz mocno tu<ch a="e"/></row>
      <row important_over="false"><ch a="H7"/>A ja uderzę mocno tam<ch a="e"/></row>
      <row important_over="false"><ch a="a"/>Na pewno runie, runie, runie<ch a="e"/></row>
      <row important_over="false"><ch a="H7"/>I wolny będzie cały świat<ch a="e"/></row>
    </block>
    <block type="verse">
      <row important_over="false"><ch a="e"/>Lecz minęło już wiele lat<ch a="H7"/><ch a="e"/></row>
      <row important_over="false"><ch a="e"/>Ręce mam starte do krwi<ch a="H7"/></row>
      <row important_over="false"><ch a="C"/>A gdy czuję że sił mi brak<ch a="H7"/><ch a="C"/><ch a="a"/></row>
      <row important_over="false"><ch a="e"/>Mur rośnie wyższy niż był<ch a="H7"/><ch a="e"/></row>
      <row important_over="false"><ch a="e"/>Wiem już, że ledwo się trzyma<ch a="H7"/><ch a="e"/></row>
      <row important_over="false"><ch a="e"/>Lecz ciężko ruszyć go stąd<ch a="H7"/></row>
      <row important_over="false"><ch a="C"/>Nawet gdy czuję przypływ sił<ch a="H7"/><ch a="C"/><ch a="a"/></row>
      <row important_over="false"><ch a="e"/>Powtórz Swisecie pieśń swą<ch a="H7"/><ch a="e"/></row>
    </block>
    <blocklink blocknb="2"/>
    <block type="verse">
      <row important_over="false"><ch a="e"/>Stary Swiset nie mówi nic<ch a="H7"/><ch a="e"/></row>
      <row important_over="false"><ch a="e"/>Słowa porwał zły wiatr<ch a="H7"/></row>
      <row important_over="false"><ch a="C"/>Dokąd on jeden tylko wie<ch a="H7"/><ch a="C"/><ch a="a"/></row>
      <row important_over="false"><ch a="e"/>Ja w bramie tkwię cały czas<ch a="H7"/><ch a="e"/></row>
      <row important_over="false"><ch a="e"/>I gdy przychodzę mówi wciąż<ch a="H7"/><ch a="e"/></row>
      <row important_over="false"><ch a="e"/>Słyszę jak rośnie mój głos<ch a="H7"/></row>
      <row important_over="false"><ch a="C"/>Śpiewamy ostatnią Swiseta pieśń<ch a="H7"/><ch a="C"/><ch a="a"/></row>
      <row important_over="false"><ch a="e"/>Tę, której nauczył nas on<ch a="H7"/><ch a="e"/></row>
    </block>
    <blocklink blocknb="2"/>
  </lyric>
  <music metre="">
    <guitar barre="0"/>
  </music>
  <status>
    <verificators/>
    <to_do/>
  </status>
</song>

=== spiewaj/songbook/songs/pl/poezja/ballada_o_nocy_czerwcowej.xml
<?xml version="1.0" encoding="utf-8"?>
<song xmlns="http://21wdh.staszic.waw.pl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://21wdh.staszic.waw.pl https://spiewaj.com/song.xsd" title="Ballada o nocy czerwcowej">
  <text_author type="solo">Konstanty Ildefons Gałczyński</text_author>
  <composer>Maryla Ochimowska - Teper</composer>
  <lyric>
    <block type="verse">
      <row important_over="false">Kiedy no<ch a="D"/>c się w powietrzu zaczy<ch a="e"/>na,</row>
      <row important_over="false">Wtedy n<ch a="G"/>oc jest jak młoda dziewczyn<ch a="D"/>a:</row>
      <row important_over="false">Wszystko cie<ch a="D"/>szy ją i wszystko śmies<ch a="e"/>zy,</row>
      <row important_over="false">Wszystko w rę<ch a="G"/>ce chciałaby brać<ch a="D"/>.</row>
    </block>
    <block type="verse">
      <row important_over="false">Diabeł du<ch a="D"/>żo jej daje w podar<ch a="e"/>ku</row>
      <row important_over="false">Gwiazd fałsz<ch a="G"/>ywych z gwiezdnego jarma<ch a="D"/>rku.</row>
      <row important_over="false">Noc te gwia<ch a="D"/>zdy do uszu przymier<ch a="e"/>za</row>
      <row important_over="false">I z gwiazda<ch a="G"/>mi chci<ch a="A7"/>ałaby spać.<ch a="D"/></row>
    </block>
    <block type="chorus">
      <bis times="2">
        <row important_over="false">Ja je<ch a="D"/>stem noc czerwcow<ch a="e"/>a.</row>
        <row important_over="false">Królo<ch a="G"/>wa jaśminow<ch a="D"/>a.</row>
        <row important_over="false">Zap<ch a="D"/>atrzcie się w moje ręc<ch a="e"/>e.</row>
        <row important_over="false">Wsłucha<ch a="A7"/>jcie się w śpiewny chód.<ch a="D"/></row>
      </bis>
    </block>
    <block type="verse">
      <row important_over="false" sidechords="D e">Ale zanim dur gwiezdny ją oplótł,</row>
      <row important_over="false" sidechords="G D">Idzie krokiem tanecznym przez ogród.</row>
      <row important_over="false" sidechords="D e">Do ogrodu przez senne ulice,</row>
      <row important_over="false" sidechords="G D">Dzwonią nocy ciężkie zausznice.</row>
    </block>
    <block type="verse">
      <row important_over="false" sidechords="D e">I po każdym tanecznym obrocie</row>
      <row important_over="false" sidechords="G D">Szmaragdami dzwonią kołki w plocie.</row>
      <row important_over="false" sidechords="D e">Wreszcie do nas pod same okna,</row>
      <row important_over="false" sidechords="G A7 D">I tak tańczy i śpiewa nam:</row>
    </block>
    <blocklink blocknb="3"/>
  </lyric>
  <keywords/>
  <genre>Poezja śpiewana</genre>
  <status>
    <done/>
    <verificators/>
  </status>
</song>

=== spiewaj/songbook/songs/pl/kabaret/plastikowa_biedronko.xml
<?xml version="1.0" encoding="utf-8"?>
<song xmlns="http://21wdh.staszic.waw.pl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://21wdh.staszic.waw.pl https://spiewaj.com/song.xsd" title="Pastikowa Biedronka">
  <lyric>
    <block type="verse">
      <row important_over="true">Gdy Cię pi<ch a="G"/>erwszy raz u<ch a="D"/>jrzałem </row>
      <row important_over="true">Wielkim t<ch a="e"/>irem zajech<ch a="C"/>ałaś </row>
      <row important_over="true">Ja się w T<ch a="G"/>obie zakoch<ch a="D"/>ałem </row>
      <row important_over="true">A Ty na m<ch a="e"/>nie nie<ch a="C"/> spojrza<ch a="G"/>łaś!</row>
    </block>
    <block type="chorus">
      <row important_over="true">Plastik<ch a="G"/>owa Biedr<ch a="D"/>onko, Ty m<ch a="e"/>oja koch<ch a="C"/>ana </row>
      <row important_over="true">Zo<ch a="G"/>stań moją ż<ch a="D"/>onką błagam Ci<ch a="e"/>ę n<ch a="C"/>a kolan<ch a="G"/>ach! </row>
    </block>
    <block type="verse">
      <row important_over="never">Gdy Cię drugi raz ujrzałem <ch a="G"/><ch a="D"/></row>
      <row important_over="never">Na sklepowej półce stałaś <ch a="e"/><ch a="C"/></row>
      <row important_over="never">Ja Ci list miłosny słałem<ch a="G"/><ch a="D"/></row>
      <row important_over="never">A Ty na mnie nie spojrzałaś! <ch a="e"/><ch a="C"/><ch a="G"/></row>
    </block>
    <blocklink blocknb="2"/>
    <block type="verse">
      <row important_over="never">Kiedy w końcu nas kupili <ch a="G"/><ch a="D"/></row>
      <row important_over="never">I do domu nas zawieźli<ch a="e"/><ch a="C"/></row>
      <row important_over="never">To Ty na mnie spoglądałaś <ch a="G"/><ch a="D"/></row>
      <row important_over="never">I się we mnie zakochałaś <ch a="e"/><ch a="C"/><ch a="G"/></row>
    </block>
    <blocklink blocknb="2"/>
    <block type="verse">
      <row important_over="never">To już koniec tej piosenki<ch a="G"/><ch a="D"/></row>
      <row important_over="never">Mój Ty widzu ukochany <ch a="e"/><ch a="C"/></row>
      <row important_over="never">Jeśli Ci się spodobała<ch a="G"/><ch a="D"/></row>
      <row important_over="never">To zaśpiewaj razem z nami! <ch a="e"/><ch a="C"/><ch a="G"/></row>
    </block>
    <blocklink blocknb="2"/>
  </lyric>
  <keywords/>
  <genre>Piosenka kabaretowa</genre>
  <status>
    <done/>
    <verificators/>
  </status>
</song>

=== spiewaj/songbook/songs/pl/poezja/Dom_wschodzacego_slonca.xml
<?xml version="1.0" encoding="utf-8"?>
<song xmlns="http://21wdh.staszic.waw.pl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://21wdh.staszic.waw.pl https://spiewaj.com/song.xsd" title="Dom wschodzącego słońca">
  <alias/>
  <text_author/>
  <comment/>
  <composer type="solo"/>
  <artist type="solo"/>
  <translator/>
  <original_title/>
  <lyric>
    <block type="verse">
      <row important_over="false"><ch a="a"/>Przez ciemne szyby zagląda już mrok<ch a="C"/><ch a="D"/><ch a="F"/></row>
      <row important_over="false"><ch a="a"/>W łóżeczku mały chłopiec śpi<ch a="C"/><ch a="E"/></row>
      <row important_over="false"><ch a="a"/>Sen jakiś dziwny wykrzywił mu twarz<ch a="C"/><ch a="D"/><ch a="F"/></row>
      <row important_over="false"><ch a="a"/>Pod powiekami lśnią łzy<ch a="E"/><ch a="a"/><ch a="E"/></row>
    </block>
    <block type="verse">
      <row important_over="false"><ch a="a"/>Wczoraj wieczorem dowiedział się że<ch a="C"/><ch a="D"/><ch a="F"/></row>
      <row important_over="false"><ch a="a"/>Jest w Orleanie taki dom<ch a="C"/><ch a="E"/></row>
      <row important_over="false"><ch a="a"/>Wschodzącym Słońcem nazywa się go<ch a="C"/><ch a="D"/><ch a="F"/></row>
      <row important_over="false"><ch a="a"/>Mieszkają w nim chłopcy jak on<ch a="E"/><ch a="a"/><ch a="E"/></row>
    </block>
    <block type="verse">
      <row important_over="false"><ch a="a"/>W oknach ma kraty przy drzwiach stoi stróż<ch a="C"/><ch a="D"/><ch a="F"/></row>
      <row important_over="false"><ch a="a"/>I patrzy wzrokiem ponurym<ch a="C"/><ch a="E"/></row>
      <row important_over="false"><ch a="a"/>Na małych chłopców więzienny ich strój<ch a="C"/><ch a="D"/><ch a="F"/></row>
      <row important_over="false"><ch a="a"/>Na ogolone głowy<ch a="E"/><ch a="a"/><ch a="E"/></row>
    </block>
    <block type="verse">
      <row important_over="false"><ch a="a"/>Ale nadzieja nie zgaśnie w nich<ch a="C"/><ch a="D"/><ch a="F"/></row>
      <row important_over="false"><ch a="a"/>Pomimo więziennych murów cel<ch a="C"/><ch a="E"/></row>
      <row important_over="false"><ch a="a"/>Wschodzące słońce zabłyśnie znów<ch a="C"/><ch a="D"/><ch a="F"/></row>
      <row important_over="false"><ch a="a"/>Nad małym domem w kraju tym<ch a="E"/><ch a="C"/></row>
    </block>
  </lyric>
  <music metre="">
    <guitar barre="0"/>
  </music>
  <status>
    <verificators/>
    <to_do/>
  </status>
</song>
